In [2]:
import numpy as np
import random as rd

In [3]:
output = np.zeros([4,4])
position = np.zeros([4,4])

In [4]:
elements = [2,4,8,16]

In [5]:
p1 = rd.randint(0,3)
p2 = rd.randint(0,3)
output[p1][p2] = elements[rd.randint(0,3)]
position[p1][p2] = 1

In [6]:
output

array([[ 0.,  0., 16.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [7]:
position

array([[0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
def add_element():
    status = 0
    for i in range(0,4):
        for j in range(0,4):
            if position[i][j] == 0:
                status = 1
                break
    if status == 1:
        while status:
            x,y = rd.randint(0,3),rd.randint(0,3)
            status = position[x][y]
        output[x][y] = elements[rd.randint(0,3)]
    else:
        print("Game Over! No space available...")
  

In [1]:
def add_element():
    status = 1
    
    while status:
        x,y = rd.randint(0,3),rd.randint(0,3)
        status = position[x][y]
    output[x][y] = elements[rd.randint(0,3)]
    position[x][y] = 1
    
    
def operation_a(score):
    for i in range(0,4):
        for j in range(1,4):
            for k in range(j,0,-1):
                if position[i][k] == 1:
                    if position[i][k-1] == 0:
                        output[i][k-1] = output[i][k]
                        output[i][k] = 0
                        position[i][k-1] = 1
                        position[i][k] = 0
                    elif output[i][k-1] == output[i][k]:
                        output[i][k-1] = output[i][k-1]*2
                        output[i][k] = 0
                        position[i][k] = 0
                        score = score + output[i][k-1]
    add_element()
    return score

def operation_d(score):
    for i in range(0,4):
        for j in range(2,-1,-1):
            for k in range(j,3):
                if position[i][k] == 1:
                    if position[i][k+1] == 0:
                        output[i][k+1] = output[i][k]
                        output[i][k] = 0
                        position[i][k+1] = 1
                        position[i][k] = 0
                    elif output[i][k+1] == output[i][k]:
                        output[i][k+1] = output[i][k+1]*2
                        output[i][k] = 0
                        position[i][k] = 0
                        score = score + output[i][k+1]
    add_element()
    return score

def operation_w(score):
    for i in range(0,4):
        for j in range(1,4):
            for k in range(j,0,-1):
                if position[k][i] == 1:
                    if position[k-1][i] == 0:
                        output[k-1][i] = output[k][i]
                        output[k][i] = 0
                        position[k-1][i] = 1
                        position[k][i] = 0
                    elif output[k-1][i] == output[k][i]:
                        output[k-1][i] = output[k-1][i]*2
                        output[k][i] = 0
                        position[k][i] = 0
                        score = score + output[k-1][i]
    add_element()
    return score

def operation_s(score):
    for i in range(0,4):
        for j in range(2,-1,-1):
            for k in range(j,3):
                if position[k][i] == 1:
                    if position[k+1][i] == 0:
                        output[k+1][i] = output[k][i]
                        output[k][i] = 0
                        position[k+1][i] = 1
                        position[k][i] = 0
                    elif output[k+1][i] == output[k][i]:
                        output[k+1][i] = output[k+1][i]*2
                        output[k][i] = 0
                        position[k][i] = 0
                        score = score + output[k+1][i]
    add_element()
    return score



In [9]:
print("*DOCUMENTATION*")
print("Use W,A,S,D to Move and E to exit()")
add_element()
score = 0
user = 1
while user!= 'E':
    print("Your Score:",int(score))
    print(output)
    user = input("Enter Operation: ").upper()
    if user == 'W':
        score = operation_w(score)
    elif user == 'A':
        score = operation_a(score)
    elif user == 'S':
        score = operation_s(score)
    elif user == 'D':
        score = operation_d(score)
        
    if score >= 2048:
        break
        
        
if score>= 2048:
    print("Congrats! You finished it.")
else:
    print("ThankYou! Its yours, You can try again!")
    

*DOCUMENTATION*
Use W,A,S,D to Move and E to exit()
Your Score: 0
[[ 0.  0. 16.  0.]
 [ 0.  0.  0.  8.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Enter Operation: a
Your Score: 0
[[16.  0.  0.  0.]
 [ 0.  0.  0.  8.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  2.]]
Enter Operation: a
Your Score: 0
[[16.  0.  0.  0.]
 [ 0.  0.  0.  8.]
 [ 0.  0.  2.  0.]
 [ 0.  0.  0.  2.]]
Enter Operation: a
Your Score: 0
[[16.  0.  0.  0.]
 [ 0.  0.  0.  8.]
 [ 0.  4.  2.  0.]
 [ 0.  0.  0.  2.]]
Enter Operation: w
Your Score: 0
[[16.  0.  0.  0.]
 [ 0.  0.  0.  8.]
 [ 0.  4. 16.  0.]
 [ 0.  0.  0.  2.]]
Enter Operation: d
Your Score: 0
[[ 0.  0.  0. 16.]
 [ 0.  0.  0.  4.]
 [ 0.  4. 16.  0.]
 [ 0.  0.  0.  2.]]
Enter Operation: d
Your Score: 0
[[ 0.  8.  0. 16.]
 [ 0.  0.  0.  4.]
 [ 0.  4. 16.  0.]
 [ 0.  0.  0.  2.]]
Enter Operation: e
ThankYou! Its yours, You can try again!


In [26]:
def operation_w(score):
    for i in range(0,3):
        for j in range(2,5):
            for k in range(1,j):
                if position[i][k-1] == 0:
                    output[i][k-1] = output[i][k]
                    position[i][k-1] = 1
                    position[i][k] = 0
                elif output[i][k-1] == output[i][k]:
                    output[i][k-1] = output[i][k-1]*2
                    position[i][k] = 0
                    score = score + output[i][k-1]
    return score
                    

In [1]:
import msvcrt 

def kbfunc():
    
    x = msvcrt.kbhit()
    if x: 
        ret = ord(msvcrt.getch()) 
    else:
        print("E")
        ret = 0 
    return ret
kbfunc()

E


0

In [2]:
from pynput.keyboard import Key, Listener

def on_press(key):
    print('{0} pressed'.format(
        key))

def on_release(key):
    print('{0} release'.format(
        key))
    if key == Key.esc:
        # Stop listener
        return False

# Collect events until released
with Listener(
        on_press=on_press,
        on_release=on_release) as listener:
    listener.join()

Key.enter release
Key.shift_r release
Key.up pressed
Key.up release
Key.up pressed
Key.up release
Key.right pressed
Key.right release
Key.down pressed
Key.down release
Key.left pressed
Key.left release
Key.esc pressed
Key.esc release


In [3]:
from pynput.keyboard import Key, Listener

def on_press(key):
    if key == key.up:
        return 'W'
    elif key == key.left:
        return 'A'
    elif key == key.down:
        return 'S'
    elif key == key.right:
        return 'D'
    elif key == key.esc or key == 'E':
        print("Exiting..")
        return True
    else:
        print("Wrong input!")

with Listener(on_press=on_press) as listener:
    a = listner.running
    print(a)

NameError: name 'listner' is not defined

In [1]:

listner = Listener(on_press=on_press)
listner.running

NameError: name 'Listener' is not defined

In [4]:
import numpy as np
import random as rd

output = np.zeros([4,4])
position = np.zeros([4,4],dtype=int)
elements = [2,4,8,16]
p1 = rd.randint(0,3)
p2 = rd.randint(0,3)
output[p1][p2] = elements[rd.randint(0,3)]
position[p1][p2] = 1

def add_element():
    status = 0
    for i in range(0,4):
        for j in range(0,4):
            if position[i][j] == 0:
                status = 1
                break
    if status == 1:
        while status:
            x,y = rd.randint(0,3),rd.randint(0,3)
            status = position[x][y]
        output[x][y] = elements[rd.randint(0,3)]
    else:
        print("Game Over! No space available...")
  
def add_element():
    status = 1
    
    while status:
        x,y = rd.randint(0,3),rd.randint(0,3)
        status = position[x][y]
    output[x][y] = elements[rd.randint(0,3)]
    position[x][y] = 1
    
    
def operation_a(score):
    for i in range(0,4):
        for j in range(1,4):
            for k in range(j,0,-1):
                if position[i][k] == 1:
                    if position[i][k-1] == 0:
                        output[i][k-1] = output[i][k]
                        output[i][k] = 0
                        position[i][k-1] = 1
                        position[i][k] = 0
                    elif output[i][k-1] == output[i][k]:
                        output[i][k-1] = output[i][k-1]*2
                        output[i][k] = 0
                        position[i][k] = 0
                        score = score + output[i][k-1]
    add_element()
    return score

def operation_d(score):
    for i in range(0,4):
        for j in range(2,-1,-1):
            for k in range(j,3):
                if position[i][k] == 1:
                    if position[i][k+1] == 0:
                        output[i][k+1] = output[i][k]
                        output[i][k] = 0
                        position[i][k+1] = 1
                        position[i][k] = 0
                    elif output[i][k+1] == output[i][k]:
                        output[i][k+1] = output[i][k+1]*2
                        output[i][k] = 0
                        position[i][k] = 0
                        score = score + output[i][k+1]
    add_element()
    return score

def operation_w(score):
    for i in range(0,4):
        for j in range(1,4):
            for k in range(j,0,-1):
                if position[k][i] == 1:
                    if position[k-1][i] == 0:
                        output[k-1][i] = output[k][i]
                        output[k][i] = 0
                        position[k-1][i] = 1
                        position[k][i] = 0
                    elif output[k-1][i] == output[k][i]:
                        output[k-1][i] = output[k-1][i]*2
                        output[k][i] = 0
                        position[k][i] = 0
                        score = score + output[k-1][i]
    add_element()
    return score

def operation_s(score):
    for i in range(0,4):
        for j in range(2,-1,-1):
            for k in range(j,3):
                if position[k][i] == 1:
                    if position[k+1][i] == 0:
                        output[k+1][i] = output[k][i]
                        output[k][i] = 0
                        position[k+1][i] = 1
                        position[k][i] = 0
                    elif output[k+1][i] == output[k][i]:
                        output[k+1][i] = output[k+1][i]*2
                        output[k][i] = 0
                        position[k][i] = 0
                        score = score + output[k+1][i]
    add_element()
    return score

print("*DOCUMENTATION*")
print("Use W,A,S,D to Move and E to exit()")
add_element()
score = 0
user = 1
with Listener(on_press=on_press) as listener:
    print("Your Score:",int(score))
    print(output)
    user = listener.
    if user == 'W':
        score = operation_w(score)
    elif user == 'A':
        score = operation_a(score)
    elif user == 'S':
        score = operation_s(score)
    elif user == 'D':
        score = operation_d(score)
    elif user == 'E':
        pass
    else:
        print("Wrong Choice Entered.. Choose again.!")
        
    if score >= 2048:
        break
        
        
if score>= 2048:
    print("Congrats! You finished it.")
else:
    print("ThankYou! Its yours, You can try again!")
    

SyntaxError: invalid syntax (<ipython-input-4-337a86132fca>, line 117)

In [5]:
import curses, time

def main(stdscr):
    """checking for keypress"""
    stdscr.nodelay(True)  # do not wait for input when calling getch
    return stdscr.getch()

while True:
    print("key:", curses.wrapper(main)) # prints: 'key: 97' for 'a' pressed
                                        # '-1' on no presses
    time.sleep(1)

ModuleNotFoundError: No module named '_curses'

In [ ]:
import msvcrt as m
a = m.getche()
a